/****************************************************** 
FileName:T_PM_PurviewInfoWebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.T_PM_PurviewInfo
{
    //=========================================================================
    //  ClassName : T_PM_PurviewInfoContants
    /// <summary>
    /// T_PM_PurviewInfo的常数类
    /// </summary>
    //=========================================================================
    public class T_PM_PurviewInfoContants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string PurviewIDFieldName = "PurviewID";
        public static readonly string PurviewIDFieldRemark = "";
    
        public static readonly string PurviewNameFieldName = "PurviewName";
        public static readonly string PurviewNameFieldRemark = "";
    
        public static readonly string PurviewTypeIDFieldName = "PurviewTypeID";
        public static readonly string PurviewTypeIDFieldRemark = "";
    
        public static readonly string PurviewContentFieldName = "PurviewContent";
        public static readonly string PurviewContentFieldRemark = "";
    
        public static readonly string PurviewRemarkFieldName = "PurviewRemark";
        public static readonly string PurviewRemarkFieldRemark = "";
    
        public static readonly string IsPageMenuFieldName = "IsPageMenu";
        public static readonly string IsPageMenuFieldRemark = "";
    
        public static readonly string PageFileNameFieldName = "PageFileName";
        public static readonly string PageFileNameFieldRemark = "";
    
        public static readonly string PageFileParameterFieldName = "PageFileParameter";
        public static readonly string PageFileParameterFieldRemark = "";
    
        public static readonly string PageFilePathFieldName = "PageFilePath";
        public static readonly string PageFilePathFieldRemark = "";
    
        public static readonly string UpdateDateFieldName = "UpdateDate";
        public static readonly string UpdateDateFieldRemark = "";
        
    
        public static readonly string AutoGenerateField = "";
        public static readonly int AutoGenerateNumberLength = 0;
        public static readonly string AutoGeneratePrefix = "";
        public static readonly bool AllowAutoGenerateID = false;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = false;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 2;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = false;
        public static readonly bool WebDetailPage = false;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "PurviewID";
        public static readonly string TitleField = "PurviewName";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
