/****************************************************** 
FileName:T_BG_0602WebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.T_BG_0602
{
    //=========================================================================
    //  ClassName : T_BG_0602Contants
    /// <summary>
    /// T_BG_0602的常数类
    /// </summary>
    //=========================================================================
    public class T_BG_0602Contants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string LMHFieldName = "LMH";
        public static readonly string LMHFieldRemark = "栏目号";
    
        public static readonly string LMMFieldName = "LMM";
        public static readonly string LMMFieldRemark = "栏目名";
    
        public static readonly string SJLMHFieldName = "SJLMH";
        public static readonly string SJLMHFieldRemark = "上级栏目";
    
        public static readonly string LMTPFieldName = "LMTP";
        public static readonly string LMTPFieldRemark = "栏目图片";
    
        public static readonly string LMNRFieldName = "LMNR";
        public static readonly string LMNRFieldRemark = "栏目显示内容";
    
        public static readonly string LMLBYSFieldName = "LMLBYS";
        public static readonly string LMLBYSFieldRemark = "栏目列表样式";
    
        public static readonly string SFLBLMFieldName = "SFLBLM";
        public static readonly string SFLBLMFieldRemark = "列表内容栏目";
    
        public static readonly string SFWBURLFieldName = "SFWBURL";
        public static readonly string SFWBURLFieldRemark = "外部栏目";
    
        public static readonly string WBURLFieldName = "WBURL";
        public static readonly string WBURLFieldRemark = "外部栏目连接";
        
    
        public static readonly string AutoGenerateField = "LMH";
        public static readonly int AutoGenerateNumberLength = 6;
        public static readonly string AutoGeneratePrefix = "LM";
        public static readonly bool AllowAutoGenerateID = true;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = true;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 2;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = true;
        public static readonly bool WebDetailPage = false;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "LMH";
        public static readonly string TitleField = "LMM";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
