/****************************************************** 
FileName:T_BM_DWXXWebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.T_BM_DWXX
{
    //=========================================================================
    //  ClassName : T_BM_DWXXContants
    /// <summary>
    /// T_BM_DWXX的常数类
    /// </summary>
    //=========================================================================
    public class T_BM_DWXXContants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string DWBHFieldName = "DWBH";
        public static readonly string DWBHFieldRemark = "单位编号";
    
        public static readonly string DWMCFieldName = "DWMC";
        public static readonly string DWMCFieldRemark = "单位名称";
    
        public static readonly string SJDWBHFieldName = "SJDWBH";
        public static readonly string SJDWBHFieldRemark = "上级单位";
    
        public static readonly string DZFieldName = "DZ";
        public static readonly string DZFieldRemark = "地址";
    
        public static readonly string YBFieldName = "YB";
        public static readonly string YBFieldRemark = "邮编";
    
        public static readonly string LXBMFieldName = "LXBM";
        public static readonly string LXBMFieldRemark = "联系部门";
    
        public static readonly string LXDHFieldName = "LXDH";
        public static readonly string LXDHFieldRemark = "联系电话";
    
        public static readonly string EmailFieldName = "Email";
        public static readonly string EmailFieldRemark = "Email";
    
        public static readonly string LXRFieldName = "LXR";
        public static readonly string LXRFieldRemark = "联系人";
    
        public static readonly string SJFieldName = "SJ";
        public static readonly string SJFieldRemark = "手机";
        
    
        public static readonly string AutoGenerateField = "DWBH";
        public static readonly int AutoGenerateNumberLength = 4;
        public static readonly string AutoGeneratePrefix = "DW";
        public static readonly bool AllowAutoGenerateID = true;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = true;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "内蒙古自治区哲学社会科学专家库信息表";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 2;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = false;
        public static readonly bool WebDetailPage = false;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "DWBH";
        public static readonly string TitleField = "DWMC";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
