/****************************************************** 
FileName:T_BG_0601WebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.T_BG_0601
{
    //=========================================================================
    //  ClassName : T_BG_0601Contants
    /// <summary>
    /// T_BG_0601的常数类
    /// </summary>
    //=========================================================================
    public class T_BG_0601Contants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string FBHFieldName = "FBH";
        public static readonly string FBHFieldRemark = "发布号";
    
        public static readonly string BTFieldName = "BT";
        public static readonly string BTFieldRemark = "标题";
    
        public static readonly string FBLMFieldName = "FBLM";
        public static readonly string FBLMFieldRemark = "发布栏目";
    
        public static readonly string FBBMFieldName = "FBBM";
        public static readonly string FBBMFieldRemark = "发布部门";
    
        public static readonly string XXLXFieldName = "XXLX";
        public static readonly string XXLXFieldRemark = "信息类型";
    
        public static readonly string XXTPDZFieldName = "XXTPDZ";
        public static readonly string XXTPDZFieldRemark = "信息图片";
    
        public static readonly string XXNRFieldName = "XXNR";
        public static readonly string XXNRFieldRemark = "信息内容";
    
        public static readonly string FJXZDZFieldName = "FJXZDZ";
        public static readonly string FJXZDZFieldRemark = "附件";
    
        public static readonly string XXZTFieldName = "XXZT";
        public static readonly string XXZTFieldRemark = "信息状态";
    
        public static readonly string IsTopFieldName = "IsTop";
        public static readonly string IsTopFieldRemark = "是否置顶";
    
        public static readonly string TopSortFieldName = "TopSort";
        public static readonly string TopSortFieldRemark = "置顶序号";
    
        public static readonly string IsBestFieldName = "IsBest";
        public static readonly string IsBestFieldRemark = "推荐";
    
        public static readonly string FBRJGHFieldName = "FBRJGH";
        public static readonly string FBRJGHFieldRemark = "发布人";
    
        public static readonly string FBSJRQFieldName = "FBSJRQ";
        public static readonly string FBSJRQFieldRemark = "发布时间";
    
        public static readonly string FBIPFieldName = "FBIP";
        public static readonly string FBIPFieldRemark = "发布IP";
        
    
        public static readonly string AutoGenerateField = "FBH";
        public static readonly int AutoGenerateNumberLength = 8;
        public static readonly string AutoGeneratePrefix = "XX";
        public static readonly bool AllowAutoGenerateID = true;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = true;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 2;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = false;
        public static readonly bool WebDetailPage = true;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "FBH";
        public static readonly string TitleField = "BT";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
