/****************************************************** 
FileName:T_PM_UserInfoWebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.T_PM_UserInfo
{
    //=========================================================================
    //  ClassName : T_PM_UserInfoContants
    /// <summary>
    /// T_PM_UserInfo的常数类
    /// </summary>
    //=========================================================================
    public class T_PM_UserInfoContants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string UserIDFieldName = "UserID";
        public static readonly string UserIDFieldRemark = "用户编号";
    
        public static readonly string UserLoginNameFieldName = "UserLoginName";
        public static readonly string UserLoginNameFieldRemark = "用户名";
    
        public static readonly string UserGroupIDFieldName = "UserGroupID";
        public static readonly string UserGroupIDFieldRemark = "用户组";
    
        public static readonly string SubjectIDFieldName = "SubjectID";
        public static readonly string SubjectIDFieldRemark = "所属单位";
    
        public static readonly string UserNickNameFieldName = "UserNickName";
        public static readonly string UserNickNameFieldRemark = "姓名";
    
        public static readonly string PasswordFieldName = "Password";
        public static readonly string PasswordFieldRemark = "密码";
    
        public static readonly string XBFieldName = "XB";
        public static readonly string XBFieldRemark = "性别";
    
        public static readonly string MZFieldName = "MZ";
        public static readonly string MZFieldRemark = "民族";
    
        public static readonly string ZZMMFieldName = "ZZMM";
        public static readonly string ZZMMFieldRemark = "政治面貌";
    
        public static readonly string SFZHFieldName = "SFZH";
        public static readonly string SFZHFieldRemark = "身份证号";
    
        public static readonly string SJHFieldName = "SJH";
        public static readonly string SJHFieldRemark = "手机";
    
        public static readonly string BGDHFieldName = "BGDH";
        public static readonly string BGDHFieldRemark = "办公电话";
    
        public static readonly string JTDHFieldName = "JTDH";
        public static readonly string JTDHFieldRemark = "家庭电话";
    
        public static readonly string EmailFieldName = "Email";
        public static readonly string EmailFieldRemark = "Email";
    
        public static readonly string QQHFieldName = "QQH";
        public static readonly string QQHFieldRemark = "QQ";
    
        public static readonly string LoginTimeFieldName = "LoginTime";
        public static readonly string LoginTimeFieldRemark = "登录时间";
    
        public static readonly string LastLoginIPFieldName = "LastLoginIP";
        public static readonly string LastLoginIPFieldRemark = "登录IP";
    
        public static readonly string LastLoginDateFieldName = "LastLoginDate";
        public static readonly string LastLoginDateFieldRemark = "上次时间";
    
        public static readonly string LoginTimesFieldName = "LoginTimes";
        public static readonly string LoginTimesFieldRemark = "登录次数";
    
        public static readonly string UserStatusFieldName = "UserStatus";
        public static readonly string UserStatusFieldRemark = "用户状态";
    
        public static readonly string vcodeFieldName = "vcode";
        public static readonly string vcodeFieldRemark = "验证码";
    
        public static readonly string lcodeFieldName = "lcode";
        public static readonly string lcodeFieldRemark = "登录码";
        
    
        public static readonly string AutoGenerateField = "UserID";
        public static readonly int AutoGenerateNumberLength = 5;
        public static readonly string AutoGeneratePrefix = "U";
        public static readonly bool AllowAutoGenerateID = true;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = true;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 2;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = false;
        public static readonly bool WebDetailPage = false;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "UserID";
        public static readonly string TitleField = "UserNickName";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
