/****************************************************** 
FileName:ShortMessageWebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.ShortMessage
{
    //=========================================================================
    //  ClassName : ShortMessageContants
    /// <summary>
    /// ShortMessage的常数类
    /// </summary>
    //=========================================================================
    public class ShortMessageContants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string DXXBTFieldName = "DXXBT";
        public static readonly string DXXBTFieldRemark = "标题";
    
        public static readonly string DXXLXFieldName = "DXXLX";
        public static readonly string DXXLXFieldRemark = "类型";
    
        public static readonly string DXXNRFieldName = "DXXNR";
        public static readonly string DXXNRFieldRemark = "内容";
    
        public static readonly string DXXFJFieldName = "DXXFJ";
        public static readonly string DXXFJFieldRemark = "附件";
    
        public static readonly string FSSJFieldName = "FSSJ";
        public static readonly string FSSJFieldRemark = "发送时间";
    
        public static readonly string FSRFieldName = "FSR";
        public static readonly string FSRFieldRemark = "发送人";
    
        public static readonly string FSBMFieldName = "FSBM";
        public static readonly string FSBMFieldRemark = "发送部门";
    
        public static readonly string FSIPFieldName = "FSIP";
        public static readonly string FSIPFieldRemark = "发送IP";
    
        public static readonly string JSRFieldName = "JSR";
        public static readonly string JSRFieldRemark = "接收人";
    
        public static readonly string SFCKFieldName = "SFCK";
        public static readonly string SFCKFieldRemark = "查看状态";
    
        public static readonly string CKSJFieldName = "CKSJ";
        public static readonly string CKSJFieldRemark = "查看时间";
        
    
        public static readonly string AutoGenerateField = "";
        public static readonly int AutoGenerateNumberLength = 0;
        public static readonly string AutoGeneratePrefix = "";
        public static readonly bool AllowAutoGenerateID = false;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = false;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 2;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = false;
        public static readonly bool WebDetailPage = true;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "FSSJ";
        public static readonly string TitleField = "DXXBT";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
