/****************************************************** 
FileName:T_PM_UserGroupInfoWebUI.cs
******************************************************/
using System;
using System.Data;

namespace RICH.Common.BM.T_PM_UserGroupInfo
{
    //=========================================================================
    //  ClassName : T_PM_UserGroupInfoContants
    /// <summary>
    /// T_PM_UserGroupInfo的常数类
    /// </summary>
    //=========================================================================
    public class T_PM_UserGroupInfoContants
    {
  
        public static readonly string ObjectIDFieldName = "ObjectID";
        public static readonly string ObjectIDFieldRemark = "";
    
        public static readonly string UserGroupIDFieldName = "UserGroupID";
        public static readonly string UserGroupIDFieldRemark = "用户组编号";
    
        public static readonly string UserGroupNameFieldName = "UserGroupName";
        public static readonly string UserGroupNameFieldRemark = "用户组名称";
    
        public static readonly string UserGroupContentFieldName = "UserGroupContent";
        public static readonly string UserGroupContentFieldRemark = "内容";
    
        public static readonly string UserGroupRemarkFieldName = "UserGroupRemark";
        public static readonly string UserGroupRemarkFieldRemark = "备注";
    
        public static readonly string DefaultPageFieldName = "DefaultPage";
        public static readonly string DefaultPageFieldRemark = "系统默认页";
    
        public static readonly string UpdateDateFieldName = "UpdateDate";
        public static readonly string UpdateDateFieldRemark = "更新时间";
        
    
        public static readonly string AutoGenerateField = "";
        public static readonly int AutoGenerateNumberLength = 0;
        public static readonly string AutoGeneratePrefix = "";
        public static readonly bool AllowAutoGenerateID = false;
        public static readonly bool AutoGenerateDay = false;
        public static readonly bool AutoGenerateHour = false;
        public static readonly bool AutoGenerateMinute = false;
        public static readonly bool AutoGenerateMonth = false;
        public static readonly bool AutoGenerateMSecond = false;
        public static readonly bool AutoGenerateSecond = false;
        public static readonly bool AutoGenerateYear = false;
        public static readonly bool AutoGenerateOrder = false;
        public static readonly bool AutoGenerateIncludeDateTime = false;
        public static readonly bool Sort = false;
        
        public static readonly bool NoTableBorder = false;
        public static readonly bool ExistPDFPageHeader = false;
        public static readonly bool ExistPDFPageFooter = false;
        public static readonly bool ExistPDFTableTitle = false;
        public static readonly string PDFPageHeader = "";
        public static readonly string PDFPageFooter = "";
        public static readonly string PDFTableTitle = "";
        public static readonly bool IsPDFCustomTitle = false;
        public static readonly string PDFCustomTitleReadField = "";
        public static readonly string PDFCustomTitle = "";
        
        public static readonly bool ImportFromDoc = false;
        public static readonly bool ImportFromDataSet = false;
        public static readonly int ImportDataSetStartLineNum = 2;
        public static readonly bool ExportToDocumentTemplate = false;
        public static readonly bool ExportToPDF = false;
        public static readonly bool CopyItem = false;
        public static readonly bool WebDetailPage = false;
        public static readonly bool UseFilterReport = false;
        
        public static readonly string SortField = "UserGroupID";
        public static readonly string TitleField = "UserGroupName";
        
        public static readonly string GetValueTextField = "";
        public static readonly string GetValueValueField = "";
        public static readonly bool GetValue = false;
        public static readonly bool GetValueByKey = false;
    }
}
  
